name: Auto Merge PR

on:
  pull_request:
    types: [opened, synchronize, labeled, ready_for_review]
  workflow_dispatch:

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Debug PR Variables
        run: |
          echo "Repository: ${{ github.event.pull_request.head.repo.full_name }}"
          echo "Labels: ${{ github.event.pull_request.labels }}"
          echo "PR Title: ${{ github.event.pull_request.title }}"
          echo "Changed Files: ${{ github.event.pull_request.changed_files }}"
          echo "Branch: ${{ github.event.pull_request.head.ref }}"

      - name: Auto merge pull request
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          gh pr merge $PR_NUMBER --merge --auto
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
