name: Track Repository Stats

on:
  schedule:
    - cron: "0 0 * * *" # 每天 UTC 00:00 執行
  workflow_dispatch: # 允許手動觸發

jobs:
  track-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dateutil

      - name: Fetch repository stats
        run: |
          python - <<EOF
          import json
          import os
          import requests
          from datetime import datetime
          import time

          print("Starting repository stats collection...")

          def get_repo_stats(owner, repo):
              print(f"Fetching stats for {owner}/{repo}")
              base_url = f"https://api.github.com/repos/{owner}/{repo}"
              
              # 獲取基本倉庫信息
              repo_response = requests.get(base_url)
              if repo_response.status_code != 200:
                  print(f"Failed to get repo info: {repo_response.status_code}")
                  return None
              
              repo_data = repo_response.json()
              
              # 獲取發布版本
              releases_response = requests.get(f"{base_url}/releases")
              releases = releases_response.json() if releases_response.status_code == 200 else []
              
              total_downloads = 0
              release_stats = []
              for release in releases:
                  release_downloads = 0
                  for asset in release["assets"]:
                      release_downloads += asset["download_count"]
                  
                  release_stats.append({
                      "tag_name": release["tag_name"],
                      "name": release["name"],
                      "downloads": release_downloads,
                      "published_at": release["published_at"]
                  })
                  total_downloads += release_downloads
              
              return {
                  "name": repo_data["name"],
                  "full_name": repo_data["full_name"],
                  "releases": {
                      "total_count": len(releases),
                      "total_downloads": total_downloads,
                      "releases": release_stats
                  },
                  "metadata": {
                      "collected_at": datetime.utcnow().isoformat()
                  }
              }

          try:
              print("Creating data directory...")
              os.makedirs("data", exist_ok=True)
              
              results = {}
              if os.path.exists("data/repository_stats.json"):
                  print("Loading existing stats file...")
                  with open("data/repository_stats.json", "r", encoding="utf-8") as f:
                      results = json.load(f)
              
              print("Checking for infos directory...")
              if os.path.exists("infos"):
                  print(f"Found infos directory, contents: {os.listdir('infos')}")
                  for filename in os.listdir("infos"):
                      if filename.endswith(".json"):
                          print(f"Processing {filename}...")
                          with open(f"infos/{filename}", "r", encoding="utf-8") as f:
                              try:
                                  data = json.load(f)
                                  print(f"JSON content: {data}")
                                  if "link" in data and "github.com" in data["link"]:
                                      parts = data["link"].strip("/").split("/")
                                      if len(parts) >= 2:
                                          owner = parts[-2]
                                          repo = parts[-1]
                                          repo_key = f"{owner}/{repo}"
                                          print(f"Found repository: {repo_key}")
                                          
                                          stats = get_repo_stats(owner, repo)
                                          if stats:
                                              results[repo_key] = stats
                                              print(f"Successfully collected stats for {repo_key}")
                                          else:
                                              print(f"Failed to get stats for {repo_key}")
                                          
                                          time.sleep(1)
                              except Exception as e:
                                  print(f"Error processing {filename}: {str(e)}")
                                  continue

              print("Saving results...")
              with open("data/repository_stats.json", "w", encoding="utf-8") as f:
                  json.dump(results, f, indent=2, ensure_ascii=False)
              print("Done!")
                  
          except Exception as e:
              print(f"Error: {str(e)}")
              raise e
          EOF

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/repository_stats.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update repository statistics [skip ci]"
          git push
